project:
  type: book
  output-dir: docs
book:
  chapters:
  - index.qmd
  - 1_OpenScholarship.qmd
  - 2_Data.qmd
  - 3_DataManagement.qmd
  - 4_InstallingR.qmd
  - 5_GettingStaRted.qmd 
  - 6_ImpoRtingData.qmd 
  - 7_VariablesFunctions.qmd 
  - 8_DescriptiveStats.qmd
  - 9_DataWrangling.qmd
  - 10_Dataviz.qmd
  - 11_Inferential.qmd
  - 12_SimpleLinearRegression.qmd
  - 13_MultipleLinearRegression.qmd
  - 14_LiterateProgramming.qmd
  - 15_PartingWords.qmd
  - 99_references.qmd
  - A_FurtherResources.qmd
  - part: "Case studies"
    chapters:
      - B_CaseStudies/Poppy/ThrowVerbs.qmd
      - B_CaseStudies/Rose-Gina/Emojis.qmd
      - B_CaseStudies/Dela/Perdon.qmd
      - B_CaseStudies/Hannah-Beyhan/Retrieval.qmd

execute:
  out-width: "90%"
  fig-width: 6
  fig-asp: 0.618

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: style.css
    code-fold: false
    code-line-numbers: false
    code-overflow: wrap
    code-tools: false
    code-link: false
    #dev: ragg_png
    dev: cairo
    #df-print: kable
    filters:
      - line-highlight
    link-external-newwindow: true
    footnotes-hover: true
    author-meta: Elen Le Foll
    include-in-header:
      - text: |
          <style>
          .cell-output-stdout code {
            word-break: break-wor !important;
            white-space: pre-wrap !important;
          }
          </style>
    from: markdown+emoji

