project:
  type: book
  output-dir: LangSciPress
book:
  chapters:
  - index.qmd
  - 1_OpenScholarship.qmd
  - 2_Data.qmd
  - 3_DataManagement.qmd
  - 4_InstallingR.qmd
  - 5_GettingStaRted.qmd 
  - 6_ImpoRtingData.qmd 
  - 7_VariablesFunctions.qmd 
  - 8_DescriptiveStats.qmd
  - 9_DataWrangling.qmd
  - 10_Dataviz.qmd 
  - 11_Inferential.qmd
  - 12_SimpleLinearRegression.qmd
  - 13_MultipleLinearRegression.qmd
  - 14_LiterateProgramming.qmd
  - 15_PartingWords.qmd
  - 99_references.qmd
  
format:
  pdf:
    toc: true
    documentclass: scrreprt
    #word-count: "{{< words-sum body-note >}}"
    keep-tex: true
    colorlinks: true
    prefer-html: true
    include-in-header:
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}

#mainfont: "DejaVu Sans" # Might help with the emojis (https://github.com/quarto-dev/quarto-cli/issues/4492)
